# Generated by Django 3.1 on 2022-04-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_feature', models.CharField(max_length=200, null=True, verbose_name='Заголовок причины')),
                ('num_feature', models.CharField(max_length=200, null=True, verbose_name='Номер причины')),
                ('text_feature', models.TextField(null=True, verbose_name='Текст причины')),
            ],
            options={
                'verbose_name': 'Причина',
                'verbose_name_plural': 'Причины',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rec', models.CharField(max_length=200, null=True, verbose_name='Заголовок рекомендации')),
                ('text_rec', models.TextField(null=True, verbose_name='Текст рекомендации')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
        migrations.CreateModel(
            name='ReserveHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_entry_date', models.CharField(max_length=50, verbose_name='Дата заезда')),
                ('res_depart_date', models.CharField(max_length=50, verbose_name='Дата выезда')),
                ('res_adult', models.IntegerField(verbose_name='Взрослые')),
                ('res_child', models.IntegerField(verbose_name='Дети')),
                ('res_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('-res_created_at',),
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('second_name', models.CharField(max_length=255, null=True)),
                ('feature', models.ManyToManyField(blank=True, related_name='features_names', to='home.Feature', verbose_name='Причины')),
                ('recommendations', models.ManyToManyField(blank=True, related_name='recommendations_names', to='home.Recommendations', verbose_name='Причины')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
    ]
